builds:
 -  
   id: MultiChecksumNL
   main: cmd/MultiChecksumNoLib/MultiChecksum.go
   binary: MultiChecksumNL 
   goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
   goarch:
    - amd64
    - 386
    - arm
    - arm64
   ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: darwin
      goarch: 386
 -  
   id: MultiChecksum
   main: cmd/MultiChecksum/Multichecksum.go
   binary: MultiChecksum 
   goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
   goarch:
    - amd64
    - 386
    - arm
    - arm64
   ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: darwin
      goarch: 386
 -  
   id: MultiChecksumBigData
   main: cmd/MultiChecksumBigData/main.go
   binary: MultiChecksumBigData
   goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
   goarch:
    - amd64
    - 386
    - arm
    - arm64
   ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: darwin
      goarch: 386
archives:
  -
    name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
